server:
  port: 9092

spring:
  application:
    name: service-account

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_account?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: hta@123

  cloud:
    # Nacos 作为注册中心的配置项
    nacos:
      discovery:
        server-addr: 127.0.0.1:15990
        namespace: 646f52b8-78a0-4e27-91df-c33c06979862


seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-tx-group
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      order-service-group: default
  config:
    type: nacos
    nacos:
      serverAddr: 127.0.0.1:15990
      dataId: "seata.properties"
      username: "nacos"
      password: "nacos"
      group: DEFAULT_GROUP
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:15990
      username: "nacos"
      password: "nacos"
      group:  DEFAULT_GROUP


# Seata 配置项，对应 SeataProperties 类
#seata:
#  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
#  tx-service-group: ${spring.application.name}-tx-group # Seata 事务组编号，用于 TC 集群名
#  # Seata 服务配置项，对应 ServiceProperties 类
#  service:
#    # 虚拟组和分组的映射
#    vgroup-mapping:
#      account-service-group: default
#  # Seata 注册中心配置项，对应 RegistryProperties 类
#  registry:
#    type: nacos # 注册中心类型，默认为 file
#    nacos:
#      cluster: default # 使用的 Seata 分组
#      namespace: # Nacos 命名空间
#      serverAddr: localhost # Nacos 服务地址
